---
title: "2T2C"
author: "Ted Aplin"
format: html
editor: visual
---

# Initialisation

## RENV (Y*ou don't need to run this every time)*

```{r}
renv::restore()
renv::status()
```

## Loading packages

```{r}
#| label: Packages
# loading packages
library(tidyverse)
library(here)

# loading personal functions
load(here("Functions", "Functions for 2T2C.R"))
```

# Data preparation

## loading

Place your data into the "Data" folder then enter it's file name here and the time interval between each frame in *Seconds.*

```{r}
#| label: File name
FileName <- "Test Results.csv"
TimeInterval <- 3
```

```{r}
#| label: Data loading
Input <- read.csv(here("Input", FileName))
Count <- as.numeric(sum(Input$Frame == 1))
ROICount <- Count/max(Input$Ch) 
Data <- Input %>% mutate(X = X - (Ch-1)*ROICount - (Frame-1)*Count)
colnames(Data) <- c("ROI", "Area", "Mean", "Min", "Max", "Channel", "Frame")
Data$Time <- (Data$Frame-1) * TimeInterval
```

## Wrangling

## calculations

# Visualisation

## All

## Individual cells
